# Station data Append
This lab is appending files for all years together

In [1]:

import pandas as pd
from pathlib import Path

folder_path = Path("../../../data/raw/Yashaswi/NL Data/")   # adjust if needed
csv_files = folder_path.glob("*.csv")

NL_all = pd.concat(
    (pd.read_csv(file, encoding="latin-1") for file in csv_files),
    ignore_index=True
)

In [2]:
NL_all.head()

,Longitude (x),Latitude (y),Station Name,Climate ID,Date/Time,Year,Month,Day,Data Quality,Max Temp (°C),...,Total Snow (cm),Total Snow Flag,Total Precip (mm),Total Precip Flag,Snow on Grnd (cm),Snow on Grnd Flag,Dir of Max Gust (10s deg),Dir of Max Gust Flag,Spd of Max Gust (km/h),Spd of Max Gust Flag
0,-54.0,47.31,ARGENTIA (AUT),8400104,1995-01-01,1995,1,1,NaN,-0.6,...,NaN,M,2.7,NaN,NaN,NaN,NaN,NaN,<31,NaN
1,-54.0,47.31,ARGENTIA (AUT),8400104,1995-01-02,1995,1,2,NaN,-1.3,...,NaN,M,3.1,NaN,NaN,NaN,NaN,NaN,<31,NaN
2,-54.0,47.31,ARGENTIA (AUT),8400104,1995-01-03,1995,1,3,NaN,1.9,...,NaN,M,17.6,NaN,NaN,NaN,NaN,NaN,<31,NaN
3,-54.0,47.31,ARGENTIA (AUT),8400104,1995-01-04,1995,1,4,NaN,1.9,...,NaN,M,NaN,M,NaN,NaN,NaN,NaN,<31,NaN
4,-54.0,47.31,ARGENTIA (AUT),8400104,1995-01-05,1995,1,5,NaN,1.9,...,NaN,M,NaN,M,NaN,NaN,NaN,NaN,<31,NaN

In [3]:
NL_all.info()

<class 'pandas.DataFrame'>
RangeIndex: 375103 entries, 0 to 375102
Data columns (total 31 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Longitude (x)              375103 non-null  float64
 1   Latitude (y)               375103 non-null  float64
 2   Station Name               375103 non-null  str
 3   Climate ID                 375103 non-null  object
 4   Date/Time                  375103 non-null  str
 5   Year                       375103 non-null  int64
 6   Month                      375103 non-null  int64
 7   Day                        375103 non-null  int64
 8   Data Quality               23290 non-null   object
 9   Max Temp (°C)              308749 non-null  float64
 10  Max Temp Flag              16685 non-null   object
 11  Min Temp (°C)              309707 non-null  float64
 12  Min Temp Flag              18208 non-null   object
 13  Mean Temp (°C)             307676 non-null  float64
 14  Mean Temp Flag             18464 non-null   object
 15  Heat Deg Days (°C)         307676 non-null  float64
 16  Heat Deg Days Flag         18464 non-null   object
 17  Cool Deg Days (°C)         307676 non-null  float64
 18  Cool Deg Days Flag         18464 non-null   object
 19  Total Rain (mm)            67435 non-null   float64
 20  Total Rain Flag            138558 non-null  object
 21  Total Snow (cm)            66837 non-null   float64
 22  Total Snow Flag            139366 non-null  object
 23  Total Precip (mm)          239869 non-null  float64
 24  Total Precip Flag          76631 non-null   object
 25  Snow on Grnd (cm)          101787 non-null  float64
 26  Snow on Grnd Flag          6236 non-null    object
 27  Dir of Max Gust (10s deg)  177258 non-null  float64
 28  Dir of Max Gust Flag       56254 non-null   object
 29  Spd of Max Gust (km/h)     215093 non-null  object
 30  Spd of Max Gust Flag       54186 non-null   object
dtypes: float64(12), int64(3), object(14), str(2)
memory usage: 88.7+ MB

In [4]:
NL_all.columns

Index(['Longitude (x)', 'Latitude (y)', 'Station Name', 'Climate ID',
       'Date/Time', 'Year', 'Month', 'Day', 'Data Quality', 'Max Temp (°C)',
       'Max Temp Flag', 'Min Temp (°C)', 'Min Temp Flag', 'Mean Temp (°C)',
       'Mean Temp Flag', 'Heat Deg Days (°C)', 'Heat Deg Days Flag',
       'Cool Deg Days (°C)', 'Cool Deg Days Flag', 'Total Rain (mm)',
       'Total Rain Flag', 'Total Snow (cm)', 'Total Snow Flag',
       'Total Precip (mm)', 'Total Precip Flag', 'Snow on Grnd (cm)',
       'Snow on Grnd Flag', 'Dir of Max Gust (10s deg)',
       'Dir of Max Gust Flag', 'Spd of Max Gust (km/h)',
       'Spd of Max Gust Flag'],
      dtype='str')

In [5]:
NL_all.shape
NL_all.head(3)

,Longitude (x),Latitude (y),Station Name,Climate ID,Date/Time,Year,Month,Day,Data Quality,Max Temp (°C),...,Total Snow (cm),Total Snow Flag,Total Precip (mm),Total Precip Flag,Snow on Grnd (cm),Snow on Grnd Flag,Dir of Max Gust (10s deg),Dir of Max Gust Flag,Spd of Max Gust (km/h),Spd of Max Gust Flag
0,-54.0,47.31,ARGENTIA (AUT),8400104,1995-01-01,1995,1,1,NaN,-0.6,...,NaN,M,2.7,NaN,NaN,NaN,NaN,NaN,<31,NaN
1,-54.0,47.31,ARGENTIA (AUT),8400104,1995-01-02,1995,1,2,NaN,-1.3,...,NaN,M,3.1,NaN,NaN,NaN,NaN,NaN,<31,NaN
2,-54.0,47.31,ARGENTIA (AUT),8400104,1995-01-03,1995,1,3,NaN,1.9,...,NaN,M,17.6,NaN,NaN,NaN,NaN,NaN,<31,NaN

In [6]:
NL_all['Spd of Max Gust (km/h)'].value_counts()

Spd of Max Gust (km/h)
<31      35026
44        5176
39        4846
41        4839
37        4797
         ...
157.0        1
156.0        1
167.0        1
152.0        1
167          1
Name: count, Length: 259, dtype: int64

In [7]:
NL_all['Spd of Max Gust (km/h)'].astype(str).str.contains(r'[<>]', na=False).sum()

np.int64(35026)

In [8]:
NL = NL_all.drop(
    columns=[
        'Month', 'Day',
        'Data Quality',
        'Max Temp Flag', 'Min Temp Flag', 'Mean Temp Flag',
        'Heat Deg Days Flag', 'Cool Deg Days Flag', 'Total Rain Flag',
        'Total Snow Flag', 'Total Precip Flag', 'Snow on Grnd Flag',
       'Spd of Max Gust Flag',  'Dir of Max Gust Flag']
)

In [9]:
NL.info()

<class 'pandas.DataFrame'>
RangeIndex: 375103 entries, 0 to 375102
Data columns (total 17 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Longitude (x)              375103 non-null  float64
 1   Latitude (y)               375103 non-null  float64
 2   Station Name               375103 non-null  str
 3   Climate ID                 375103 non-null  object
 4   Date/Time                  375103 non-null  str
 5   Year                       375103 non-null  int64
 6   Max Temp (°C)              308749 non-null  float64
 7   Min Temp (°C)              309707 non-null  float64
 8   Mean Temp (°C)             307676 non-null  float64
 9   Heat Deg Days (°C)         307676 non-null  float64
 10  Cool Deg Days (°C)         307676 non-null  float64
 11  Total Rain (mm)            67435 non-null   float64
 12  Total Snow (cm)            66837 non-null   float64
 13  Total Precip (mm)          239869 non-null  float64
 14  Snow on Grnd (cm)          101787 non-null  float64
 15  Dir of Max Gust (10s deg)  177258 non-null  float64
 16  Spd of Max Gust (km/h)     215093 non-null  object
dtypes: float64(12), int64(1), object(2), str(2)
memory usage: 48.7+ MB

In [10]:
NL['Date/Time'] = pd.to_datetime(NL['Date/Time'])

In [11]:
NL['Station Name'] = NL['Station Name'].astype('string')

In [12]:
NL['Climate ID'] = NL['Climate ID'].astype('string')

In [13]:
NL['Climate ID'].unique()

<StringArray>
['8400104', '8400301', '8400416', '8400506', '8400601', '8400801', '8400812',
 '8401000', '8401295', '8401298', '8401300', '8401405', '8401500', '8401502',
 '8401538', '8401565', '8401703', '8401705', '8402520', '8402544', '8402757',
 '8402980', '8403255', '8403389', '8403399', '8403505', '8403603', '8403619',
 '8403801', '8403820', '8403851', '8404025', '8404242', '8404343', '840B053',
 '840BR7C', '840KN90', '8501106', '8501131', '8501136', '8501900', '8501915',
 '8502400', '8502580', '8502592', '8502799', '8502801', '8502810', '8503249',
 '8504176', '8504177']
Length: 51, dtype: string

In [14]:
NL.info()

<class 'pandas.DataFrame'>
RangeIndex: 375103 entries, 0 to 375102
Data columns (total 17 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Longitude (x)              375103 non-null  float64
 1   Latitude (y)               375103 non-null  float64
 2   Station Name               375103 non-null  string
 3   Climate ID                 375103 non-null  string
 4   Date/Time                  375103 non-null  datetime64[us]
 5   Year                       375103 non-null  int64
 6   Max Temp (°C)              308749 non-null  float64
 7   Min Temp (°C)              309707 non-null  float64
 8   Mean Temp (°C)             307676 non-null  float64
 9   Heat Deg Days (°C)         307676 non-null  float64
 10  Cool Deg Days (°C)         307676 non-null  float64
 11  Total Rain (mm)            67435 non-null   float64
 12  Total Snow (cm)            66837 non-null   float64
 13  Total Precip (mm)          239869 non-null  float64
 14  Snow on Grnd (cm)          101787 non-null  float64
 15  Dir of Max Gust (10s deg)  177258 non-null  float64
 16  Spd of Max Gust (km/h)     215093 non-null  object
dtypes: datetime64[us](1), float64(12), int64(1), object(1), string(2)
memory usage: 48.7+ MB

In [15]:
NL.to_csv("NL_30Y_clean.csv", index=False)