# Station data Append
This lab is appending files for all years together

In [1]:

import pandas as pd
from pathlib import Path

folder_path = Path("../../data/raw/Yashaswi/NB data/")   # adjust if needed
csv_files = folder_path.glob("*.csv")

NB_all = pd.concat(
    (pd.read_csv(file, encoding="latin-1") for file in csv_files),
    ignore_index=True
)

In [2]:
NB_all.head()

,Longitude (x),Latitude (y),Station Name,Climate ID,Date/Time,Year,Month,Day,Data Quality,Max Temp (°C),...,Total Snow (cm),Total Snow Flag,Total Precip (mm),Total Precip Flag,Snow on Grnd (cm),Snow on Grnd Flag,Dir of Max Gust (10s deg),Dir of Max Gust Flag,Spd of Max Gust (km/h),Spd of Max Gust Flag
0,-67.72,46.71,AROOSTOOK,8100300,1995-01-01,1995,1,1,NaN,-8.0,...,1.2,NaN,1.2,NaN,32.0,NaN,NaN,NaN,NaN,NaN
1,-67.72,46.71,AROOSTOOK,8100300,1995-01-02,1995,1,2,NaN,-4.0,...,1.8,NaN,1.8,NaN,33.0,NaN,NaN,NaN,NaN,NaN
2,-67.72,46.71,AROOSTOOK,8100300,1995-01-03,1995,1,3,NaN,-6.0,...,0.0,NaN,0.0,NaN,34.0,NaN,NaN,NaN,NaN,NaN
3,-67.72,46.71,AROOSTOOK,8100300,1995-01-04,1995,1,4,NaN,-3.0,...,2.2,NaN,2.2,NaN,34.0,NaN,NaN,NaN,NaN,NaN
4,-67.72,46.71,AROOSTOOK,8100300,1995-01-05,1995,1,5,NaN,-9.0,...,0.0,NaN,0.0,NaN,35.0,NaN,NaN,NaN,NaN,NaN

In [3]:
NB_all.info()

<class 'pandas.DataFrame'>
RangeIndex: 204073 entries, 0 to 204072
Data columns (total 31 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Longitude (x)              204073 non-null  float64
 1   Latitude (y)               204073 non-null  float64
 2   Station Name               204073 non-null  str
 3   Climate ID                 204073 non-null  int64
 4   Date/Time                  204073 non-null  str
 5   Year                       204073 non-null  int64
 6   Month                      204073 non-null  int64
 7   Day                        204073 non-null  int64
 8   Data Quality               26540 non-null   object
 9   Max Temp (°C)              168883 non-null  float64
 10  Max Temp Flag              3348 non-null    object
 11  Min Temp (°C)              169349 non-null  float64
 12  Min Temp Flag              3580 non-null    object
 13  Mean Temp (°C)             168574 non-null  float64
 14  Mean Temp Flag             3832 non-null    object
 15  Heat Deg Days (°C)         168574 non-null  float64
 16  Heat Deg Days Flag         3832 non-null    object
 17  Cool Deg Days (°C)         168574 non-null  float64
 18  Cool Deg Days Flag         3832 non-null    object
 19  Total Rain (mm)            48126 non-null   float64
 20  Total Rain Flag            59440 non-null   object
 21  Total Snow (cm)            46689 non-null   float64
 22  Total Snow Flag            61133 non-null   object
 23  Total Precip (mm)          172207 non-null  float64
 24  Total Precip Flag          14470 non-null   object
 25  Snow on Grnd (cm)          93230 non-null   float64
 26  Snow on Grnd Flag          4277 non-null    object
 27  Dir of Max Gust (10s deg)  73698 non-null   float64
 28  Dir of Max Gust Flag       10604 non-null   object
 29  Spd of Max Gust (km/h)     99222 non-null   object
 30  Spd of Max Gust Flag       10074 non-null   object
dtypes: float64(12), int64(4), object(13), str(2)
memory usage: 48.3+ MB

In [4]:
NB_all.columns

Index(['Longitude (x)', 'Latitude (y)', 'Station Name', 'Climate ID',
       'Date/Time', 'Year', 'Month', 'Day', 'Data Quality', 'Max Temp (°C)',
       'Max Temp Flag', 'Min Temp (°C)', 'Min Temp Flag', 'Mean Temp (°C)',
       'Mean Temp Flag', 'Heat Deg Days (°C)', 'Heat Deg Days Flag',
       'Cool Deg Days (°C)', 'Cool Deg Days Flag', 'Total Rain (mm)',
       'Total Rain Flag', 'Total Snow (cm)', 'Total Snow Flag',
       'Total Precip (mm)', 'Total Precip Flag', 'Snow on Grnd (cm)',
       'Snow on Grnd Flag', 'Dir of Max Gust (10s deg)',
       'Dir of Max Gust Flag', 'Spd of Max Gust (km/h)',
       'Spd of Max Gust Flag'],
      dtype='str')

In [5]:
NB_all.shape
NB_all.head(3)

,Longitude (x),Latitude (y),Station Name,Climate ID,Date/Time,Year,Month,Day,Data Quality,Max Temp (°C),...,Total Snow (cm),Total Snow Flag,Total Precip (mm),Total Precip Flag,Snow on Grnd (cm),Snow on Grnd Flag,Dir of Max Gust (10s deg),Dir of Max Gust Flag,Spd of Max Gust (km/h),Spd of Max Gust Flag
0,-67.72,46.71,AROOSTOOK,8100300,1995-01-01,1995,1,1,NaN,-8.0,...,1.2,NaN,1.2,NaN,32.0,NaN,NaN,NaN,NaN,NaN
1,-67.72,46.71,AROOSTOOK,8100300,1995-01-02,1995,1,2,NaN,-4.0,...,1.8,NaN,1.8,NaN,33.0,NaN,NaN,NaN,NaN,NaN
2,-67.72,46.71,AROOSTOOK,8100300,1995-01-03,1995,1,3,NaN,-6.0,...,0.0,NaN,0.0,NaN,34.0,NaN,NaN,NaN,NaN,NaN

In [6]:
NB_all['Spd of Max Gust (km/h)'].value_counts()

Spd of Max Gust (km/h)
<31      24915
32        3747
33        3316
35        3209
37        3151
         ...
15           1
137          1
128          1
111.0        1
109.0        1
Name: count, Length: 159, dtype: int64

In [7]:
NB_all['Spd of Max Gust (km/h)'].astype(str).str.contains(r'[<>]', na=False).sum()

np.int64(24915)

In [8]:
NB = NB_all.drop(
    columns=[
        'Month', 'Day',
        'Data Quality',
        'Max Temp Flag', 'Min Temp Flag', 'Mean Temp Flag',
        'Heat Deg Days Flag', 'Cool Deg Days Flag', 'Total Rain Flag',
        'Total Snow Flag', 'Total Precip Flag', 'Snow on Grnd Flag',
       'Spd of Max Gust Flag',  'Dir of Max Gust Flag']
)

In [9]:
NB.info()

<class 'pandas.DataFrame'>
RangeIndex: 204073 entries, 0 to 204072
Data columns (total 17 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Longitude (x)              204073 non-null  float64
 1   Latitude (y)               204073 non-null  float64
 2   Station Name               204073 non-null  str
 3   Climate ID                 204073 non-null  int64
 4   Date/Time                  204073 non-null  str
 5   Year                       204073 non-null  int64
 6   Max Temp (°C)              168883 non-null  float64
 7   Min Temp (°C)              169349 non-null  float64
 8   Mean Temp (°C)             168574 non-null  float64
 9   Heat Deg Days (°C)         168574 non-null  float64
 10  Cool Deg Days (°C)         168574 non-null  float64
 11  Total Rain (mm)            48126 non-null   float64
 12  Total Snow (cm)            46689 non-null   float64
 13  Total Precip (mm)          172207 non-null  float64
 14  Snow on Grnd (cm)          93230 non-null   float64
 15  Dir of Max Gust (10s deg)  73698 non-null   float64
 16  Spd of Max Gust (km/h)     99222 non-null   object
dtypes: float64(12), int64(2), object(1), str(2)
memory usage: 26.5+ MB

In [10]:
NB['Date/Time'] = pd.to_datetime(NB['Date/Time'])

In [11]:
NB['Station Name'] = NB['Station Name'].astype('string')

In [12]:
NB['Climate ID'] = NB['Climate ID'].astype('string')

In [13]:
NB['Climate ID'].value_counts().sort_index()

Climate ID
8100300    11337
8100467    12418
8100468    11688
8100506     3287
8100885     8401
8100989     8063
8101201     5113
8101303     8429
8101505     6209
8101605     9862
8101746    12081
8101792     5844
8101925     9862
8102326     4046
8102536    11715
8102848     7698
8103050    11688
8103201     5479
8103202     2922
8103780     5844
8104201    11688
8104295     6237
8104901     5479
8104905     1826
8104935     7698
8105210     4411
8105603     4748
Name: count, dtype: Int64

In [14]:
NB.info()

<class 'pandas.DataFrame'>
RangeIndex: 204073 entries, 0 to 204072
Data columns (total 17 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Longitude (x)              204073 non-null  float64
 1   Latitude (y)               204073 non-null  float64
 2   Station Name               204073 non-null  string
 3   Climate ID                 204073 non-null  string
 4   Date/Time                  204073 non-null  datetime64[us]
 5   Year                       204073 non-null  int64
 6   Max Temp (°C)              168883 non-null  float64
 7   Min Temp (°C)              169349 non-null  float64
 8   Mean Temp (°C)             168574 non-null  float64
 9   Heat Deg Days (°C)         168574 non-null  float64
 10  Cool Deg Days (°C)         168574 non-null  float64
 11  Total Rain (mm)            48126 non-null   float64
 12  Total Snow (cm)            46689 non-null   float64
 13  Total Precip (mm)          172207 non-null  float64
 14  Snow on Grnd (cm)          93230 non-null   float64
 15  Dir of Max Gust (10s deg)  73698 non-null   float64
 16  Spd of Max Gust (km/h)     99222 non-null   object
dtypes: datetime64[us](1), float64(12), int64(1), object(1), string(2)
memory usage: 26.5+ MB

In [15]:
NB.to_csv("NB_30Y_clean.csv", index=False)