# Station data Append
This lab is appending files for all years together

In [1]:

import pandas as pd
from pathlib import Path

folder_path = Path("../../data/raw/Yashaswi/NS Data/")   # adjust if needed
csv_files = folder_path.glob("*.csv")

NS_all = pd.concat(
    (pd.read_csv(file, encoding="latin-1") for file in csv_files),
    ignore_index=True
)

In [2]:
NS_all.head()

,Longitude (x),Latitude (y),Station Name,Climate ID,Date/Time,Year,Month,Day,Data Quality,Max Temp (°C),...,Total Snow (cm),Total Snow Flag,Total Precip (mm),Total Precip Flag,Snow on Grnd (cm),Snow on Grnd Flag,Dir of Max Gust (10s deg),Dir of Max Gust Flag,Spd of Max Gust (km/h),Spd of Max Gust Flag
0,-65.47,43.45,BACCARO PT,8200255,2007-01-01,2007,1,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-65.47,43.45,BACCARO PT,8200255,2007-01-02,2007,1,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-65.47,43.45,BACCARO PT,8200255,2007-01-03,2007,1,3,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-65.47,43.45,BACCARO PT,8200255,2007-01-04,2007,1,4,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,-65.47,43.45,BACCARO PT,8200255,2007-01-05,2007,1,5,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
NS_all.info()

<class 'pandas.DataFrame'>
RangeIndex: 341950 entries, 0 to 341949
Data columns (total 31 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Longitude (x)              341950 non-null  float64
 1   Latitude (y)               341950 non-null  float64
 2   Station Name               341950 non-null  str
 3   Climate ID                 341950 non-null  int64
 4   Date/Time                  341950 non-null  str
 5   Year                       341950 non-null  int64
 6   Month                      341950 non-null  int64
 7   Day                        341950 non-null  int64
 8   Data Quality               10429 non-null   object
 9   Max Temp (°C)              285904 non-null  float64
 10  Max Temp Flag              10499 non-null   object
 11  Min Temp (°C)              286922 non-null  float64
 12  Min Temp Flag              11138 non-null   object
 13  Mean Temp (°C)             285307 non-null  float64
 14  Mean Temp Flag             11537 non-null   object
 15  Heat Deg Days (°C)         285307 non-null  float64
 16  Heat Deg Days Flag         11537 non-null   object
 17  Cool Deg Days (°C)         285307 non-null  float64
 18  Cool Deg Days Flag         11537 non-null   object
 19  Total Rain (mm)            48260 non-null   float64
 20  Total Rain Flag            103909 non-null  object
 21  Total Snow (cm)            46889 non-null   float64
 22  Total Snow Flag            105587 non-null  object
 23  Total Precip (mm)          224813 non-null  float64
 24  Total Precip Flag          50220 non-null   object
 25  Snow on Grnd (cm)          93787 non-null   float64
 26  Snow on Grnd Flag          7285 non-null    object
 27  Dir of Max Gust (10s deg)  172434 non-null  float64
 28  Dir of Max Gust Flag       25948 non-null   object
 29  Spd of Max Gust (km/h)     209186 non-null  object
 30  Spd of Max Gust Flag       25200 non-null   object
dtypes: float64(12), int64(4), object(13), str(2)
memory usage: 80.9+ MB

In [4]:
NS_all.columns

Index(['Longitude (x)', 'Latitude (y)', 'Station Name', 'Climate ID',
       'Date/Time', 'Year', 'Month', 'Day', 'Data Quality', 'Max Temp (°C)',
       'Max Temp Flag', 'Min Temp (°C)', 'Min Temp Flag', 'Mean Temp (°C)',
       'Mean Temp Flag', 'Heat Deg Days (°C)', 'Heat Deg Days Flag',
       'Cool Deg Days (°C)', 'Cool Deg Days Flag', 'Total Rain (mm)',
       'Total Rain Flag', 'Total Snow (cm)', 'Total Snow Flag',
       'Total Precip (mm)', 'Total Precip Flag', 'Snow on Grnd (cm)',
       'Snow on Grnd Flag', 'Dir of Max Gust (10s deg)',
       'Dir of Max Gust Flag', 'Spd of Max Gust (km/h)',
       'Spd of Max Gust Flag'],
      dtype='str')

In [5]:
NS_all.shape
NS_all.head(3)

,Longitude (x),Latitude (y),Station Name,Climate ID,Date/Time,Year,Month,Day,Data Quality,Max Temp (°C),...,Total Snow (cm),Total Snow Flag,Total Precip (mm),Total Precip Flag,Snow on Grnd (cm),Snow on Grnd Flag,Dir of Max Gust (10s deg),Dir of Max Gust Flag,Spd of Max Gust (km/h),Spd of Max Gust Flag
0,-65.47,43.45,BACCARO PT,8200255,2007-01-01,2007,1,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-65.47,43.45,BACCARO PT,8200255,2007-01-02,2007,1,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-65.47,43.45,BACCARO PT,8200255,2007-01-03,2007,1,3,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
NS_all['Spd of Max Gust (km/h)'].value_counts()

Spd of Max Gust (km/h)
<31      35516
32        5577
37        5352
35        5322
33        5215
         ...
150          1
154          1
158.0        1
20           1
139.0        1
Name: count, Length: 240, dtype: int64

In [7]:
NS_all['Spd of Max Gust (km/h)'].astype(str).str.contains(r'[<>]', na=False).sum()

np.int64(35516)

In [8]:
NS = NS_all.drop(
    columns=[
        'Month', 'Day',
        'Data Quality',
        'Max Temp Flag', 'Min Temp Flag', 'Mean Temp Flag',
        'Heat Deg Days Flag', 'Cool Deg Days Flag', 'Total Rain Flag',
        'Total Snow Flag', 'Total Precip Flag', 'Snow on Grnd Flag',
       'Spd of Max Gust Flag',  'Dir of Max Gust Flag']
)

In [9]:
NS.info()

<class 'pandas.DataFrame'>
RangeIndex: 341950 entries, 0 to 341949
Data columns (total 17 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Longitude (x)              341950 non-null  float64
 1   Latitude (y)               341950 non-null  float64
 2   Station Name               341950 non-null  str
 3   Climate ID                 341950 non-null  int64
 4   Date/Time                  341950 non-null  str
 5   Year                       341950 non-null  int64
 6   Max Temp (°C)              285904 non-null  float64
 7   Min Temp (°C)              286922 non-null  float64
 8   Mean Temp (°C)             285307 non-null  float64
 9   Heat Deg Days (°C)         285307 non-null  float64
 10  Cool Deg Days (°C)         285307 non-null  float64
 11  Total Rain (mm)            48260 non-null   float64
 12  Total Snow (cm)            46889 non-null   float64
 13  Total Precip (mm)          224813 non-null  float64
 14  Snow on Grnd (cm)          93787 non-null   float64
 15  Dir of Max Gust (10s deg)  172434 non-null  float64
 16  Spd of Max Gust (km/h)     209186 non-null  object
dtypes: float64(12), int64(2), object(1), str(2)
memory usage: 44.4+ MB

In [10]:
NS['Date/Time'] = pd.to_datetime(NS['Date/Time'])

In [11]:
NS['Station Name'] = NS['Station Name'].astype('string')

In [12]:
NS['Climate ID'] = NS['Climate ID'].astype('string')

In [13]:
NS['Climate ID'].value_counts().sort_index()

Climate ID
8200255     7333
8200558    11716
8200573     3287
8200574     3315
8200604     8035
8200774    11688
8200828     3287
8201001     4383
8201390     8794
8201780     5844
8201969     8035
8202000    11688
8202240     3287
8202249     2922
8202251     5479
8202252     3315
8202255     3287
8202318    11716
8202502     9862
8202592    11716
8202810    11323
8202896    10227
8203163     3680
8203210     8035
8203405     9862
8203478     8035
8203702     8766
8204020     2191
8204154     3680
8204161    10620
8204190     3287
8204193     8035
8204402     8429
8204453    11716
8204495     6237
8204703     4748
8204708     3652
8204909    11688
8205090     4748
8205092     6968
8205093     3287
8205130     3315
8205701     4748
8205702     7670
8205703     3287
8205895     8794
8206240    11688
8206491     5479
8206495     5479
8206496     3287
Name: count, dtype: Int64

In [14]:
NS.info()

<class 'pandas.DataFrame'>
RangeIndex: 341950 entries, 0 to 341949
Data columns (total 17 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Longitude (x)              341950 non-null  float64
 1   Latitude (y)               341950 non-null  float64
 2   Station Name               341950 non-null  string
 3   Climate ID                 341950 non-null  string
 4   Date/Time                  341950 non-null  datetime64[us]
 5   Year                       341950 non-null  int64
 6   Max Temp (°C)              285904 non-null  float64
 7   Min Temp (°C)              286922 non-null  float64
 8   Mean Temp (°C)             285307 non-null  float64
 9   Heat Deg Days (°C)         285307 non-null  float64
 10  Cool Deg Days (°C)         285307 non-null  float64
 11  Total Rain (mm)            48260 non-null   float64
 12  Total Snow (cm)            46889 non-null   float64
 13  Total Precip (mm)          224813 non-null  float64
 14  Snow on Grnd (cm)          93787 non-null   float64
 15  Dir of Max Gust (10s deg)  172434 non-null  float64
 16  Spd of Max Gust (km/h)     209186 non-null  object
dtypes: datetime64[us](1), float64(12), int64(1), object(1), string(2)
memory usage: 44.4+ MB

In [15]:
NS.to_csv("NS_30Y_clean.csv", index=False)