# Monthly Precipitation Data Cleaning – ECCC

This notebook performs data inspection, cleaning, and preparation of monthly precipitation data from Environment and Climate Change Canada (ECCC).

Scope of this notebook (Week 2):
- Monthly climate data
- Total Precipitation (mm)
- Nova Scotia weather stations
- Data wrangling and cleaning only (no analysis or modeling)

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load raw monthly climate data: Yarmouth station
file_path = "../Capstone/raw data/en_climate_monthly_NS_8205090_1944-2007_P1M_SHEARWATER.csv"
df_raw = pd.read_csv(file_path)

In [3]:
# Initial inspection of raw data
df_raw.head()
df_raw.info()
df_raw.describe(include="all")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 759 entries, 0 to 758
Data columns (total 29 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Longitude (x)               759 non-null    float64
 1   Latitude (y)                759 non-null    float64
 2   Station Name                759 non-null    object
 3   Climate ID                  759 non-null    int64
 4   Date/Time                   759 non-null    object
 5   Year                        759 non-null    int64
 6   Month                       759 non-null    int64
 7   Mean Max Temp (°C)          757 non-null    float64
 8   Mean Max Temp Flag          25 non-null     object
 9   Mean Min Temp (°C)          757 non-null    float64
 10  Mean Min Temp Flag          25 non-null     object
 11  Mean Temp (°C)              757 non-null    float64
 12  Mean Temp Flag              25 non-null     object
 13  Extr Max Temp (°C)          757 non-null    float64
 14  Extr Max Temp Flag          95 non-null     object
 15  Extr Min Temp (°C)          757 non-null    float64
 16  Extr Min Temp Flag          130 non-null    object
 17  Total Rain (mm)             757 non-null    float64
 18  Total Rain Flag             27 non-null     object
 19  Total Snow (cm)             757 non-null    float64
 20  Total Snow Flag             81 non-null     object
 21  Total Precip (mm)           757 non-null    float64
 22  Total Precip Flag           26 non-null     object
 23  Snow Grnd Last Day (cm)     625 non-null    float64
 24  Snow Grnd Last Day Flag     129 non-null    object
 25  Dir of Max Gust (10's deg)  561 non-null    float64
 26  Dir of Max Gust Flag        78 non-null     object
 27  Spd of Max Gust (km/h)      562 non-null    float64
 28  Spd of Max Gust Flag        106 non-null    object
dtypes: float64(13), int64(3), object(13)
memory usage: 172.1+ KB

,Longitude (x),Latitude (y),Station Name,Climate ID,Date/Time,Year,Month,Mean Max Temp (°C),Mean Max Temp Flag,Mean Min Temp (°C),...,Total Snow (cm),Total Snow Flag,Total Precip (mm),Total Precip Flag,Snow Grnd Last Day (cm),Snow Grnd Last Day Flag,Dir of Max Gust (10's deg),Dir of Max Gust Flag,Spd of Max Gust (km/h),Spd of Max Gust Flag
count,759.0,7.590000e+02,759,759.0,759,759.000000,759.000000,757.000000,25,757.000000,...,757.000000,81,757.000000,26,625.000000,129,561.000000,78,562.000000,106
unique,NaN,NaN,1,NaN,759,NaN,NaN,NaN,3,NaN,...,NaN,4,NaN,3,NaN,3,NaN,5,NaN,5
top,NaN,NaN,SHEARWATER A,NaN,1944-01,NaN,NaN,NaN,E,NaN,...,NaN,T,NaN,E,NaN,M,NaN,S,NaN,S
freq,NaN,NaN,759,NaN,1,NaN,NaN,NaN,18,NaN,...,NaN,63,NaN,15,NaN,67,NaN,30,NaN,57
mean,-63.5,4.463000e+01,NaN,8205090.0,NaN,1975.126482,6.482213,10.905680,NaN,2.629723,...,15.724306,NaN,115.985469,NaN,1.945600,NaN,20.673797,NaN,76.622776,NaN
std,0.0,2.346337e-13,NaN,0.0,NaN,18.271041,3.459435,8.197829,NaN,7.979493,...,24.654004,NaN,53.899032,NaN,5.870143,NaN,9.826286,NaN,18.915707,NaN
min,-63.5,4.463000e+01,NaN,8205090.0,NaN,1944.000000,1.000000,-4.900000,NaN,-13.400000,...,0.000000,NaN,3.000000,NaN,0.000000,NaN,1.000000,NaN,35.000000,NaN
25%,-63.5,4.463000e+01,NaN,8205090.0,NaN,1959.000000,3.000000,3.000000,NaN,-4.600000,...,0.000000,NaN,75.900000,NaN,0.000000,NaN,11.000000,NaN,64.000000,NaN
50%,-63.5,4.463000e+01,NaN,8205090.0,NaN,1975.000000,6.000000,10.400000,NaN,3.000000,...,0.000000,NaN,111.000000,NaN,0.000000,NaN,20.000000,NaN,74.000000,NaN
75%,-63.5,4.463000e+01,NaN,8205090.0,NaN,1991.000000,9.000000,18.900000,NaN,9.900000,...,25.200000,NaN,145.500000,NaN,0.000000,NaN,29.000000,NaN,87.000000,NaN
max,-63.5,4.463000e+01,NaN,8205090.0,NaN,2007.000000,12.000000,24.600000,NaN,15.900000,...,140.700000,NaN,366.900000,NaN,61.000000,NaN,36.000000,NaN,148.000000,NaN

The raw dataset contains multiple climate variables.
For the purposes of Week 2, only the Total Precipitation (mm) field is retained to demonstrate data cleaning and preparation steps.

In [4]:
# Selecting relevant columns only
columns_to_keep = [
    "Year",
    "Month",
    "Total Precip (mm)"
]

df = df_raw[columns_to_keep].copy()
df.head()

   Year  Month  Total Precip (mm)
0  1944      1                NaN
1  1944      2                NaN
2  1944      3              145.5
3  1944      4              104.6
4  1944      5                7.6

In [5]:
# Rename columns for consistency and ease of use
df.columns = [
    "year",
    "month",
    "total_precip_mm"
]

In [6]:
# Data type cleaning
df["year"] = pd.to_numeric(df["year"], errors="coerce")
df["month"] = pd.to_numeric(df["month"], errors="coerce")
df["total_precip_mm"] = pd.to_numeric(df["total_precip_mm"], errors="coerce")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 759 entries, 0 to 758
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   year             759 non-null    int64
 1   month            759 non-null    int64
 2   total_precip_mm  757 non-null    float64
dtypes: float64(1), int64(2)
memory usage: 17.9 KB

In [7]:
# Check missing values
df.isna().sum()

year               0
month              0
total_precip_mm    2
dtype: int64

In [8]:
# Remove records with missing precipitation or incomplete date information
df = df.dropna(subset=["year", "month", "total_precip_mm"])

# Convert year and month to integer after removing invalid values
df["year"] = df["year"].astype(int)
df["month"] = df["month"].astype(int)

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 757 entries, 2 to 758
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   year             757 non-null    int64
 1   month            757 non-null    int64
 2   total_precip_mm  757 non-null    float64
dtypes: float64(1), int64(2)
memory usage: 23.7 KB

In [9]:
# Check for duplicate records
df.duplicated().sum()

np.int64(0)

Records with missing precipitation values or incomplete date information were removed to produce a clean and consistent monthly dataset suitable for trend analysis. No duplicate values found.

In [10]:
# Basic outlier inspection for precipitation
df["total_precip_mm"].describe()

count    757.000000
mean     115.985469
std       53.899032
min        3.000000
25%       75.900000
50%      111.000000
75%      145.500000
max      366.900000
Name: total_precip_mm, dtype: float64

In [11]:
# Inspect extreme values using quantiles
df["total_precip_mm"].quantile([0.01, 0.99])

0.01     24.012
0.99    258.728
Name: total_precip_mm, dtype: float64

Potential outliers in monthly precipitation were inspected using summary statistics.
Extreme values were retained at this stage, as they may represent valid climatic events rather than data errors.
Outlier handling will be revisited during the analysis phase if required.

In [12]:
# Create a proper date field for temporal consistency
df["date"] = pd.to_datetime(
    df["year"].astype(str) + "-" + df["month"].astype(str) + "-01"
)

df.head()

   year  month  total_precip_mm       date
2  1944      3            145.5 1944-03-01
3  1944      4            104.6 1944-04-01
4  1944      5              7.6 1944-05-01
5  1944      6            153.4 1944-06-01
6  1944      7             50.0 1944-07-01

In [13]:
# Final inspection of cleaned dataset
df.info()

# Save cleaned dataset for further analysis and visualization
output_path = "../Capstone/clean data/precipitation_monthly_clean_shearwater.csv"
df.to_csv(output_path, index=False)

output_path
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 757 entries, 2 to 758
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   year             757 non-null    int64
 1   month            757 non-null    int64
 2   total_precip_mm  757 non-null    float64
 3   date             757 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2)
memory usage: 29.6 KB

   year  month  total_precip_mm       date
2  1944      3            145.5 1944-03-01
3  1944      4            104.6 1944-04-01
4  1944      5              7.6 1944-05-01
5  1944      6            153.4 1944-06-01
6  1944      7             50.0 1944-07-01

This cleaned dataset will be used in subsequent analysis and visualization steps.
Daily climate observations may be incorporated later to extend the time series beyond 2012 if required.