# Monthly Precipitation Data Cleaning – ECCC

This notebook performs data inspection, cleaning, and preparation of monthly precipitation data from Environment and Climate Change Canada (ECCC).

Scope of this notebook (Week 2):
- Monthly climate data
- Total Precipitation (mm)
- Nova Scotia weather stations
- Data wrangling and cleaning only (no analysis or modeling)

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load raw monthly climate data: Yarmouth station
file_path = "../Capstone/raw data/en_climate_monthly_NS_8205700_1941-2014_P1M_SYDNEY.csv"
df_raw = pd.read_csv(file_path)

In [3]:
# Initial inspection of raw data
df_raw.head()
df_raw.info()
df_raw.describe(include="all")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 882 entries, 0 to 881
Data columns (total 29 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Longitude (x)               882 non-null    float64
 1   Latitude (y)                882 non-null    float64
 2   Station Name                882 non-null    object
 3   Climate ID                  882 non-null    int64
 4   Date/Time                   882 non-null    object
 5   Year                        882 non-null    int64
 6   Month                       882 non-null    int64
 7   Mean Max Temp (°C)          863 non-null    float64
 8   Mean Max Temp Flag          7 non-null      object
 9   Mean Min Temp (°C)          862 non-null    float64
 10  Mean Min Temp Flag          8 non-null      object
 11  Mean Temp (°C)              861 non-null    float64
 12  Mean Temp Flag              9 non-null      object
 13  Extr Max Temp (°C)          864 non-null    float64
 14  Extr Max Temp Flag          78 non-null     object
 15  Extr Min Temp (°C)          864 non-null    float64
 16  Extr Min Temp Flag          139 non-null    object
 17  Total Rain (mm)             864 non-null    float64
 18  Total Rain Flag             7 non-null      object
 19  Total Snow (cm)             864 non-null    float64
 20  Total Snow Flag             77 non-null     object
 21  Total Precip (mm)           864 non-null    float64
 22  Total Precip Flag           6 non-null      object
 23  Snow Grnd Last Day (cm)     792 non-null    float64
 24  Snow Grnd Last Day Flag     59 non-null     object
 25  Dir of Max Gust (10's deg)  629 non-null    float64
 26  Dir of Max Gust Flag        156 non-null    object
 27  Spd of Max Gust (km/h)      642 non-null    object
 28  Spd of Max Gust Flag        185 non-null    object
dtypes: float64(12), int64(3), object(14)
memory usage: 200.0+ KB

,Longitude (x),Latitude (y),Station Name,Climate ID,Date/Time,Year,Month,Mean Max Temp (°C),Mean Max Temp Flag,Mean Min Temp (°C),...,Total Snow (cm),Total Snow Flag,Total Precip (mm),Total Precip Flag,Snow Grnd Last Day (cm),Snow Grnd Last Day Flag,Dir of Max Gust (10's deg),Dir of Max Gust Flag,Spd of Max Gust (km/h),Spd of Max Gust Flag
count,8.820000e+02,8.820000e+02,882,882.0,882,882.000000,882.000000,863.000000,7,862.000000,...,864.000000,77,864.000000,6,792.00000,59,629.000000,156,642,185
unique,NaN,NaN,1,NaN,882,NaN,NaN,NaN,2,NaN,...,NaN,3,NaN,2,NaN,2,NaN,4,69,4
top,NaN,NaN,SYDNEY A,NaN,1941-01,NaN,NaN,NaN,M,NaN,...,NaN,T,NaN,M,NaN,T,NaN,E,74,E
freq,NaN,NaN,882,NaN,1,NaN,NaN,NaN,4,NaN,...,NaN,71,NaN,3,NaN,56,NaN,109,31,110
mean,-6.005000e+01,4.617000e+01,NaN,8205700.0,NaN,1977.251701,6.479592,10.320278,NaN,1.414153,...,23.955787,NaN,119.953588,NaN,4.72601,NaN,21.813990,NaN,NaN,NaN
std,7.962594e-13,1.023762e-12,NaN,0.0,NaN,21.230643,3.453951,8.881168,NaN,7.944826,...,34.990407,NaN,56.169350,NaN,12.48805,NaN,8.494775,NaN,NaN,NaN
min,-6.005000e+01,4.617000e+01,NaN,8205700.0,NaN,1941.000000,1.000000,-5.200000,NaN,-15.600000,...,0.000000,NaN,17.800000,NaN,0.00000,NaN,1.000000,NaN,NaN,NaN
25%,-6.005000e+01,4.617000e+01,NaN,8205700.0,NaN,1959.000000,3.000000,1.900000,NaN,-5.175000,...,0.000000,NaN,77.500000,NaN,0.00000,NaN,16.000000,NaN,NaN,NaN
50%,-6.005000e+01,4.617000e+01,NaN,8205700.0,NaN,1977.000000,6.000000,9.700000,NaN,1.500000,...,2.300000,NaN,115.100000,NaN,0.00000,NaN,21.000000,NaN,NaN,NaN
75%,-6.005000e+01,4.617000e+01,NaN,8205700.0,NaN,1996.000000,9.000000,18.650000,NaN,8.175000,...,40.950000,NaN,151.625000,NaN,1.00000,NaN,29.000000,NaN,NaN,NaN
max,-6.005000e+01,4.617000e+01,NaN,8205700.0,NaN,2014.000000,12.000000,26.900000,NaN,16.100000,...,181.600000,NaN,442.500000,NaN,94.00000,NaN,36.000000,NaN,NaN,NaN

The raw dataset contains multiple climate variables.
For the purposes of Week 2, only the Total Precipitation (mm) field is retained to demonstrate data cleaning and preparation steps.

In [4]:
# Selecting relevant columns only
columns_to_keep = [
    "Year",
    "Month",
    "Total Precip (mm)"
]

df = df_raw[columns_to_keep].copy()
df.head()

   Year  Month  Total Precip (mm)
0  1941      1                NaN
1  1941      2                NaN
2  1941      3                NaN
3  1941      4              115.6
4  1941      5              141.5

In [5]:
# Rename columns for consistency and ease of use
df.columns = [
    "year",
    "month",
    "total_precip_mm"
]

In [6]:
# Data type cleaning
df["year"] = pd.to_numeric(df["year"], errors="coerce")
df["month"] = pd.to_numeric(df["month"], errors="coerce")
df["total_precip_mm"] = pd.to_numeric(df["total_precip_mm"], errors="coerce")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 882 entries, 0 to 881
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   year             882 non-null    int64
 1   month            882 non-null    int64
 2   total_precip_mm  864 non-null    float64
dtypes: float64(1), int64(2)
memory usage: 20.8 KB

In [7]:
# Check missing values
df.isna().sum()

year                0
month               0
total_precip_mm    18
dtype: int64

In [8]:
# Remove records with missing precipitation or incomplete date information
df = df.dropna(subset=["year", "month", "total_precip_mm"])

# Convert year and month to integer after removing invalid values
df["year"] = df["year"].astype(int)
df["month"] = df["month"].astype(int)

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 864 entries, 3 to 881
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   year             864 non-null    int64
 1   month            864 non-null    int64
 2   total_precip_mm  864 non-null    float64
dtypes: float64(1), int64(2)
memory usage: 27.0 KB

In [9]:
# Check for duplicate records
df.duplicated().sum()

np.int64(0)

Records with missing precipitation values or incomplete date information were removed to produce a clean and consistent monthly dataset suitable for trend analysis. No duplicate values found.

In [10]:
# Basic outlier inspection for precipitation
df["total_precip_mm"].describe()

count    864.000000
mean     119.953588
std       56.169350
min       17.800000
25%       77.500000
50%      115.100000
75%      151.625000
max      442.500000
Name: total_precip_mm, dtype: float64

In [11]:
# Inspect extreme values using quantiles
df["total_precip_mm"].quantile([0.01, 0.99])

0.01     24.778
0.99    268.532
Name: total_precip_mm, dtype: float64

Potential outliers in monthly precipitation were inspected using summary statistics.
Extreme values were retained at this stage, as they may represent valid climatic events rather than data errors.
Outlier handling will be revisited during the analysis phase if required.

In [12]:
# Create a proper date field for temporal consistency
df["date"] = pd.to_datetime(
    df["year"].astype(str) + "-" + df["month"].astype(str) + "-01"
)

df.head()

   year  month  total_precip_mm       date
3  1941      4            115.6 1941-04-01
4  1941      5            141.5 1941-05-01
5  1941      6             63.8 1941-06-01
6  1941      7             66.5 1941-07-01
7  1941      8             83.1 1941-08-01

In [13]:
# Final inspection of cleaned dataset
df.info()

# Save cleaned dataset for further analysis and visualization
output_path = "../Capstone/clean data/precipitation_monthly_clean_sydney.csv"
df.to_csv(output_path, index=False)

output_path
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 864 entries, 3 to 881
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   year             864 non-null    int64
 1   month            864 non-null    int64
 2   total_precip_mm  864 non-null    float64
 3   date             864 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2)
memory usage: 33.8 KB

   year  month  total_precip_mm       date
3  1941      4            115.6 1941-04-01
4  1941      5            141.5 1941-05-01
5  1941      6             63.8 1941-06-01
6  1941      7             66.5 1941-07-01
7  1941      8             83.1 1941-08-01

This cleaned dataset will be used in subsequent analysis and visualization steps.
Daily climate observations may be incorporated later to extend the time series beyond 2012 if required.