In [9]:
import pandas as pd
import numpy as np


df_aylesford = pd.read_csv(
    r"C:\Users\mickl\AQI\Nova_Scotia_level_Ozone_O3Aylesford.csv"
)

In [10]:
df_aylesford.head()
df_aylesford.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 262992 entries, 0 to 262991
Data columns (total 5 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Date & Time  262992 non-null  object
 1   Pollutant    262992 non-null  object
 2   Unit         262992 non-null  object
 3   Station      262992 non-null  object
 4   Average      240895 non-null  float64
dtypes: float64(1), object(4)
memory usage: 10.0+ MB

In [15]:
aylesford = df_aylesford.copy()

In [17]:
aylesford = aylesford[["Date & Time", "Average"]]

In [19]:
#  Rename columns
aylesford = aylesford.rename(
    columns={
        "Date & Time": "Date",
        "Average": "Concentration"
    }
)
aylesford.head()

                     Date  Concentration
0  2022/01/01 12:00:00 AM           23.5
1  2022/01/01 01:00:00 AM           23.6
2  2022/01/01 02:00:00 AM           25.0
3  2022/01/01 03:00:00 AM           23.8
4  2022/01/01 04:00:00 AM           24.6

In [22]:
# Remove nulls
aylesford = aylesford.dropna()

In [23]:
# Remove invalid (negative) concentrations

aylesford = aylesford[aylesford["Concentration"] >= 0]

In [26]:
#Standardize Date (NO hour)
aylesford["Date"] = pd.to_datetime(
    aylesford["Date"], errors="coerce"
).dt.date
# Drop any failed conversions
aylesford = aylesford.dropna(subset=["Date"])

In [30]:
#Add AQI columns
aylesford["Pollutant"] = "O3"
aylesford["Station"] = "Aylesford"
aylesford.info()
aylesford.head()

<class 'pandas.core.frame.DataFrame'>
Index: 240895 entries, 0 to 262991
Data columns (total 4 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           240895 non-null  object
 1   Concentration  240895 non-null  float64
 2   Pollutant      240895 non-null  object
 3   Station        240895 non-null  object
dtypes: float64(1), object(3)
memory usage: 9.2+ MB

         Date  Concentration Pollutant    Station
0  2022-01-01           23.5        O3  Aylesford
1  2022-01-01           23.6        O3  Aylesford
2  2022-01-01           25.0        O3  Aylesford
3  2022-01-01           23.8        O3  Aylesford
4  2022-01-01           24.6        O3  Aylesford

In [31]:
aylesford.to_csv(
    r"C:\Users\mickl\AQI\Aylesford_O3_Staging.csv",
    index=False
)

In [32]:
df_pictou = pd.read_csv(
    r"C:\Users\mickl\AQI\Nova_Scotia_level_Ozone_O3Pictou.csv"
)

In [39]:
pictou = df_pictou.copy()
pictou = pictou[["Date & Time", "Average"]]

#Rename columns for AQI correctness
pictou = pictou.rename(
    columns={
        "Date & Time": "Date",
        "Average": "Concentration"
    }
)

In [45]:
# Remove null values
pictou = pictou.dropna()
# Remove invalid (negative) concentrations
pictou = pictou[pictou["Concentration"] >= 0]

In [50]:
#Standardize the Date column (no datetime / no hour)
pictou["Date"] = pd.to_datetime(
    pictou["Date"], errors="coerce"
).dt.date

#Remove bad parses
pictou = pictou.dropna(subset=["Date"])

In [56]:
# Add AQI metadata columns
pictou["Pollutant"] = "O3"
pictou["Station"] = "Pictou"
pictou.info()
pictou.head()

<class 'pandas.core.frame.DataFrame'>
Index: 183800 entries, 0 to 219166
Data columns (total 4 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           183800 non-null  object
 1   Concentration  183800 non-null  float64
 2   Pollutant      183800 non-null  object
 3   Station        183800 non-null  object
dtypes: float64(1), object(3)
memory usage: 7.0+ MB

         Date  Concentration Pollutant Station
0  2022-01-01           15.5        O3  Pictou
1  2022-01-01           12.6        O3  Pictou
2  2022-01-01           11.1        O3  Pictou
3  2022-01-01           10.8        O3  Pictou
4  2022-01-01           13.5        O3  Pictou

In [57]:
pictou.to_csv(
    r"C:\Users\mickl\AQI\Pictou_O3_Staging.csv",
    index=False
)

In [59]:
df_port_hawkesbury = pd.read_csv(
    r"C:\Users\mickl\AQI\Nova_Scotia_level_Ozone_O3Port_Hawkesbury.csv"
)

In [63]:
port_hawkesbury = df_port_hawkesbury.copy()
#Select the correct columns
port_hawkesbury = port_hawkesbury[["Date & Time", "Average"]]
# Rename columns for AQI use
port_hawkesbury = port_hawkesbury.rename(
    columns={
        "Date & Time": "Date",
        "Average": "Concentration"
    }
)
port_hawkesbury.head()

                     Date  Concentration
0  2022/01/01 12:00:00 AM           18.0
1  2022/01/01 01:00:00 AM           21.8
2  2022/01/01 02:00:00 AM           23.5
3  2022/01/01 03:00:00 AM           26.1
4  2022/01/01 04:00:00 AM           26.6

In [65]:
# Remove null values
port_hawkesbury = port_hawkesbury.dropna()
#  Remove invalid (negative) concentrations
port_hawkesbury = port_hawkesbury[port_hawkesbury["Concentration"] >= 0]

In [68]:
# Standardize the Date column
port_hawkesbury["Date"] = pd.to_datetime(
    port_hawkesbury["Date"], errors="coerce"
).dt.date
# Drop failed conversions
port_hawkesbury = port_hawkesbury.dropna(subset=["Date"])

In [72]:
# Add AQI metadata columns
port_hawkesbury["Pollutant"] = "O3"
port_hawkesbury["Station"] = "Port Hawkesbury"
port_hawkesbury.info()
port_hawkesbury.head()

<class 'pandas.core.frame.DataFrame'>
Index: 125186 entries, 0 to 131494
Data columns (total 4 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           125186 non-null  object
 1   Concentration  125186 non-null  float64
 2   Pollutant      125186 non-null  object
 3   Station        125186 non-null  object
dtypes: float64(1), object(3)
memory usage: 4.8+ MB

         Date  Concentration Pollutant          Station
0  2022-01-01           18.0        O3  Port Hawkesbury
1  2022-01-01           21.8        O3  Port Hawkesbury
2  2022-01-01           23.5        O3  Port Hawkesbury
3  2022-01-01           26.1        O3  Port Hawkesbury
4  2022-01-01           26.6        O3  Port Hawkesbury

In [73]:
port_hawkesbury.to_csv(
    r"C:\Users\mickl\AQI\Port_Hawkesbury_O3_Staging.csv",
    index=False
)

In [74]:
df_sydney_no2 = pd.read_csv(
    r"C:\Users\mickl\AQI\Nova_Scotia_Nitrogen_Oxides_NO2Sydney.csv"
)

In [79]:
#Creating a working copy
sydney_no2 = df_sydney_no2.copy()

# Select required columns
sydney_no2 = sydney_no2[["Date & Time", "Average"]]

# Rename columns for AQI correctness
sydney_no2 = sydney_no2.rename(
    columns={
        "Date & Time": "Date",
        "Average": "Concentration"
    }
)

# Remove null values
sydney_no2 = sydney_no2.dropna()

# Remove invalid (negative) concentrations
sydney_no2 = sydney_no2[sydney_no2["Concentration"] >= 0]

In [84]:
# Standardize the Date column
sydney_no2["Date"] = pd.to_datetime(
    sydney_no2["Date"], errors="coerce"
).dt.date

# Drop failed date parses
sydney_no2 = sydney_no2.dropna(subset=["Date"])

# Add AQI metadata columns
sydney_no2["Pollutant"] = "NO2"
sydney_no2["Station"] = "Sydney"

sydney_no2.info()
sydney_no2.head()

<class 'pandas.core.frame.DataFrame'>
Index: 436229 entries, 0 to 524098
Data columns (total 4 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           436229 non-null  object
 1   Concentration  436229 non-null  float64
 2   Pollutant      436229 non-null  object
 3   Station        436229 non-null  object
dtypes: float64(1), object(3)
memory usage: 16.6+ MB

         Date  Concentration Pollutant Station
0  2022-01-01           12.7       NO2  Sydney
1  2022-01-01           11.8       NO2  Sydney
2  2022-01-01            7.2       NO2  Sydney
3  2022-01-01            6.2       NO2  Sydney
4  2022-01-01            5.1       NO2  Sydney

In [85]:
sydney_no2.to_csv(
    r"C:\Users\mickl\AQI\Sydney_NO2_Staging.csv",
    index=False
)

In [93]:
df_sable_island_so2 = pd.read_csv(
    r"C:\Users\mickl\AQI\Nova_Scotia_Sulphur_Dioxide_SO2Sable_Island.csv"
)
# Create a working copy
sable_island_so2 = df_sable_island_so2.copy()

In [95]:
# Select required columns
sable_island_so2 = sable_island_so2[["Date & Time", "Average"]]

# Rename columns for AQI correctness
sable_island_so2 = sable_island_so2.rename(
    columns={
        "Date & Time": "Date",
        "Average": "Concentration"
    }
)

In [102]:
# Remove null values
sable_island_so2 = sable_island_so2.dropna()

# Remove invalid (negative) concentrations
sable_island_so2 = sable_island_so2[sable_island_so2["Concentration"] >= 0]

# Standardize the Date column (no datetime)
sable_island_so2["Date"] = pd.to_datetime(
    sable_island_so2["Date"], errors="coerce"
).dt.date

# Drop failed conversions
sable_island_so2 = sable_island_so2.dropna(subset=["Date"])

# Add AQI metadata columns
sable_island_so2["Pollutant"] = "SO2"
sable_island_so2["Station"] = "Sable Island"

sable_island_so2.info()
sable_island_so2.head()

<class 'pandas.core.frame.DataFrame'>
Index: 41960 entries, 0 to 52583
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           41960 non-null  object
 1   Concentration  41960 non-null  float64
 2   Pollutant      41960 non-null  object
 3   Station        41960 non-null  object
dtypes: float64(1), object(3)
memory usage: 1.6+ MB

         Date  Concentration Pollutant       Station
0  2009-07-03            0.0       SO2  Sable Island
1  2014-05-17            0.0       SO2  Sable Island
2  2014-05-13            0.0       SO2  Sable Island
3  2009-10-21            0.0       SO2  Sable Island
4  2014-05-25            0.0       SO2  Sable Island

In [103]:
sable_island_so2.to_csv(
    r"C:\Users\mickl\AQI\Sable_Island_SO2_Staging.csv",
    index=False
)

In [105]:
staging_air_quality = pd.concat(
    [
        aylesford,
        pictou,
        port_hawkesbury,
        sydney_no2,
        sable_island_so2
    ],
    ignore_index=True
)

In [107]:
staging_air_quality.info()
staging_air_quality.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1028070 entries, 0 to 1028069
Data columns (total 4 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   Date           1028070 non-null  object
 1   Concentration  1028070 non-null  float64
 2   Pollutant      1028070 non-null  object
 3   Station        1028070 non-null  object
dtypes: float64(1), object(3)
memory usage: 31.4+ MB

         Date  Concentration Pollutant    Station
0  2022-01-01           23.5        O3  Aylesford
1  2022-01-01           23.6        O3  Aylesford
2  2022-01-01           25.0        O3  Aylesford
3  2022-01-01           23.8        O3  Aylesford
4  2022-01-01           24.6        O3  Aylesford

In [108]:
staging_air_quality["Pollutant"].value_counts()

Station
Sydney             436229
Aylesford          240895
Pictou             183800
Port Hawkesbury    125186
Sable Island        41960
Name: count, dtype: int64

In [113]:
staging_air_quality["Pollutant"].value_counts()

Pollutant
O3     549881
NO2    436229
SO2     41960
Name: count, dtype: int64

In [111]:
staging_air_quality["Station"].value_counts()

Station
Sydney             436229
Aylesford          240895
Pictou             183800
Port Hawkesbury    125186
Sable Island        41960
Name: count, dtype: int64

In [112]:
staging_air_quality.to_csv(
    r"C:\Users\mickl\AQI\NovaScotia_AirQuality_Staging.csv",
    index=False
)